[[redirects]]
from = "/dicas-de-seguranca-iphone-confira/"
to = "/dicas-de-seguranca-iphone-confira"
status = 301

[[redirects]]
from = "/trocar-seu-antigo-celular-pelo-iphone/"
to = "/trocar-seu-antigo-celular-pelo-iphone"
status = 301

[[redirects]]
from = "/economizar-bateria-do-iphone/"
to = "/economizar-bateria-do-iphone"
status = 301

[[redirects]]
from = "/iphone-de-vitrine/"
to = "/iphone-de-vitrine"
status = 301

[[redirects]]
from = "/setup-gamer-rosa-dicas-para-montar-o-seu/"
to = "/setup-gamer-rosa-dicas-para-montar-o-seu"
status = 301

[[redirects]]
from = "/iphone-vs-android/"
to = "/iphone-vs-android"
status = 301

[[redirects]]
from = "/por-que-o-iphone-e-tao-bom/"
to = "/por-que-o-iphone-e-tao-bom"
status = 301

[[redirects]]
from = "/setup-gamer-aprenda-como-escolher-e-montar/"
to = "/setup-gamer-aprenda-como-escolher-e-montar"
status = 301

[[redirects]]
from = "/porque-o-iphone-esquenta-entenda/"
to = "/porque-o-iphone-esquenta-entenda"
status = 301

[[redirects]]
from = "/como-proteger-o-iphone-de-roubo-confira-as-dicas/"
to = "/como-proteger-o-iphone-de-roubo-confira-as-dicas"
status = 301

[[redirects]]
from = "/jogos-para-notebook-confira-5-opcoes/"
to = "/jogos-para-notebook-confira-5-opcoes"
status = 301

[[redirects]]
from = "/peliculas-para-iphone-13/"
to = "/peliculas-para-iphone-13"
status = 301

[[redirects]]
from = "/mulheres-gamer/"
to = "/mulheres-gamer"
status = 301

[[redirects]]
from = "/quais-sao-os-melhores-fones-de-ouvido-sem-fio/"
to = "/quais-sao-os-melhores-fones-de-ouvido-sem-fio"
status = 301

[[redirects]]
from = "/poltrona-gamer-x-cadeira-game/"
to = "/poltrona-gamer-x-cadeira-game"
status = 301

[[redirects]]
from = "/pelicula-para-camera-de-iphone/"
to = "/pelicula-para-camera-de-iphone"
status = 301

[[redirects]]
from = "/pelicula-de-privacidade-para-iphone/"
to = "/pelicula-de-privacidade-para-iphone"
status = 301

[[redirects]]
from = "/carregador-turbo-iphone/"
to = "/carregador-turbo-iphone"
status = 301

[[redirects]]
from = "/top-5-melhores-acessorios-para-iphone-em-2022/"
to = "/top-5-melhores-acessorios-para-iphone-em-2022"
status = 301

[[redirects]]
from = "/melhores-fones-de-ouvido-bluetooth/"
to = "/melhores-fones-de-ouvido-bluetooth"
status = 301

[[redirects]]
from = "/carregador-para-iphone/"
to = "/carregador-para-iphone"
status = 301

[[redirects]]
from = "/acessorios-para-iphone/"
to = "/acessorios-para-iphone"
status = 301

[[redirects]]
from = "/teclado-mecanico-branco-modelos/"
to = "/teclado-mecanico-branco-modelos"
status = 301

[[redirects]]
from = "/jbl-original/"
to = "/jbl-original"
status = 301

[[redirects]]
from = "/fone-in-ear/"
to = "/fone-in-ear"
status = 301

[[redirects]]
from = "/teclado-rgb/"
to = "/teclado-rgb"
status = 301

[[redirects]]
from = "/o-que-e-um-streamer/"
to = "/o-que-e-um-streamer"
status = 301

[[redirects]]
from = "/e-sports-games/"
to = "/e-sports-games"
status = 301

[[redirects]]
from = "/pelicula-x-one-garantia/"
to = "/pelicula-x-one-garantia"
status = 301

[[redirects]]
from = "/perifericos-gamer/"
to = "/perifericos-gamer"
status = 301

[[redirects]]
from = "/edifier-w800bt-plus-review/"
to = "/edifier-w800bt-plus-review"
status = 301

[[redirects]]
from = "/pelicula-x-one-vale-a-pena/"
to = "/pelicula-x-one-vale-a-pena"
status = 301


